export const questionArray = [
    {
      text: "Q1",
      answer1: "A1",
      answer2: "A2",
      answer3: "A3",
      answer4: "A4",
    },
    {
      text: "Q2",
      answer1: "A1",
      answer2: "A2",
      answer3: "A3",
      answer4: "A4",
    },
    {
      text: "Q3",
      answer1: "A1",
      answer2: "A2",
      answer3: "A3",
      answer4: "A4",
    },
    {
      text: "Q4",
      answer1: "A1",
      answer2: "A2",
      answer3: "A3",
      answer4: "A4",
    },
    {
      text: "Q5",
      answer1: "A1",
      answer2: "A2",
      answer3: "A3",
      answer4: "A4",
    },
    {
      text: "Q6",
      answer1: "A1",
      answer2: "A2",
      answer3: "A3",
      answer4: "A4",
    },
    {
      text: "Q7",
      answer1: "A1",
      answer2: "A2",
      answer3: "A3",
      answer4: "A4",
    },
    {
      text: "Q8",
      answer1: "A1",
      answer2: "A2",
      answer3: "A3",
      answer4: "A4",
    },
        {
      text: "Q9",
      answer1: "A1",
      answer2: "A2",
      answer3: "A3",
      answer4: "A4",
    },
    {
      text: "Q10",
      answer1: "A1",
      answer2: "A2",
      answer3: "A3",
      answer4: "A4",
    },
    {
      text: "Q11",
      answer1: "A1",
      answer2: "A2",
      answer3: "A3",
      answer4: "A4",
    },
    {
      text: "Q12",
      answer1: "A1",
      answer2: "A2",
      answer3: "A3",
      answer4: "A4",
    },
    {
      text: "Q13",
      answer1: "A1",
      answer2: "A2",
      answer3: "A3",
      answer4: "A4",
    },
    {
      text: "Q14",
      answer1: "A1",
      answer2: "A2",
      answer3: "A3",
      answer4: "A4",
    },
    {
      text: "Q15",
      answer1: "A1",
      answer2: "A2",
      answer3: "A3",
      answer4: "A4",
    }]